# github action workflow file

name: Task

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# run every day
  schedule:
    - cron: '0 0 * * *'


jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Python   
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        uses: actions/checkout@v4
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run script
        uses: actions/checkout@v4
        env: 
          mktoken : ${{ secrets.mktoken }}
          mkdomain : ${{ secrets.domain }}
        run: |
          python DEL.py
       